### PR TITLE
Different fix for the timer

### PR DESCRIPTION
**Pull request by gyurco**
I would test it with Bad Dudes, but I didn't found it in your public repos.

### CODE REVIEW

**Comment by jotego** [comment]
This works well in Dragon Ninja! Thanks a lot.

**Comment by jotego** [comment]
By the way, I applied these changes to JT12 and that fixed a problem in *The Speed Rumbler* 
Thank you!
https://github.com/jotego/jt_gng/issues/81

**Comment by gyurco** [comment]
Cool! That means Genesis also affected? Or only YM2203?

**Comment by jotego** [comment]
Genesis could be affected because it is the same timer block in the end. I am afraid to try!
I know that some Konami titles were tricky and depended on the free running section to work correctly.

**Comment by gyurco** [comment]
I tried, and the results are not that bad:
Titan Overdrive 2 still works perfectly.
This very stupid demo is fixed!
https://www.pouet.net/prod.php?which=81513

I'll release it to check if the few remaining MiST users will report something.

**Comment by jotego** [comment]
Good to hear we fixed something! BTW, I heard from three MiSTer users last week that they had got a MiST too.

**Comment by gyurco** [comment]
Then maybe that was the last chance to get one, as I see, Lotharek is out of stock and ManuFerHi also doesn't make more Misticas.

**Pull request merged**
